# Dedicated Xen dom0 + DRAKVUF (hypervisor-level VMI tracing) research box.
# See ~/Git/xen-drakvuf-nix for the project this supports. Headless -- no
# desktop/Hyprland profile, unlike desktopm/io/etc.
{ self, inputs, ... }:
{
  imports = [
    ./disko.nix
    ./hardware-configuration.nix
    "${self}/modules/virtualisation/xen-dom0.nix"
    inputs.xen-drakvuf-nix.nixosModules.drakvuf-sandbox
  ];

  networking.hostName = "xenhost";

  # hardware-configuration.nix (generated by nixos-anywhere during deploy,
  # now imported above) sets this too -- kept here as well since it was
  # already relied on before that file existed; harmless, same value.
  nixpkgs.hostPlatform = "x86_64-linux";

  services.drakvuf-sandbox = {
    enable = true;
    package = inputs.xen-drakvuf-nix.packages.x86_64-linux.drakvuf;
  };

  environment.systemPackages = [
    inputs.xen-drakvuf-nix.packages.x86_64-linux.drakvuf
  ];

  hardware.cpu.intel.updateMicrocode = true;

  services.openssh.enable = true;

  users.users.root.openssh.authorizedKeys.keyFiles = [ ../../secrets/yubikey.pub ];
  users.users.icey = {
    isNormalUser = true;
    extraGroups = [ "wheel" ];
    openssh.authorizedKeys.keyFiles = [ ../../secrets/yubikey.pub ];
  };

  nix.settings.experimental-features = [
    "nix-command"
    "flakes"
  ];

  system.stateVersion = "26.05";
}
