name: Check

on: [push, pull_request, workflow_dispatch]

jobs:
  checks:
    name: Check expressions
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}}
      - uses: DeterminateSystems/magic-nix-cache-action@v3
      - run: nix flake check
