name: Check

on: [push, pull_request, workflow_dispatch]

jobs:
  checks:
    name: Check expressions
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      - uses: cachix/install-nix-action@v27
        with:
          install_url: https://nixos.org/nix/install
          extra_nix_config: |
            auto-optimise-store = true
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            experimental-features = nix-command flakes
      - uses: DeterminateSystems/magic-nix-cache-action@v7
      - run: nix flake check
